files:
  - source: "/content/**/**/*.[yaml/md]"
    ignore:
      - "**/collection/**/**"
      - "**/blog/**/**"
      - "**/*.collection.*"
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
