files:
  - source: /content/**/**/*.yaml
    ignore:
      - '**/collection/**/**'
      - '**/*.collection.*'
      - '*.zh.yaml'
      - '*.de.yaml'
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
